name: Forge Tests Gas Report

on:
  push:
    branches:
      - main
      -spoke
  pull_request:

permissions: write-all

jobs:
  check:
    name: Gas report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run Forge build
        run: |
          forge --version
          make sizes
        id: build

      - name: Run Forge tests with gas report
        run: make gas-report profile=ci
        env:
          # make fuzzing semi-deterministic to avoid noisy gas cost estimation
          # due to non-deterministic fuzzing (but still use pseudo-random fuzzing seeds)
          FOUNDRY_FUZZ_SEED: 0x${{ github.event.pull_request.base.sha || github.sha }}
          MNEMONIC: ${{ secrets.MNEMONIC_FOR_TESTS }}

      - name: Compare gas reports
        uses: Rubilmax/foundry-gas-diff@v3.16
        id: gas_diff

      - name: Add gas diff to sticky comment
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          # delete the comment in case changes no longer impact gas costs
          delete: ${{ !steps.gas_diff.outputs.markdown }}
          message: ${{ steps.gas_diff.outputs.markdown }}
